[project]
name = "contact-birthday-book"
version = "0.1.0"
description = "Contact book with birthday reminders"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "prompt-toolkit>=3.0.52",
    "pyside6>=6.10.0",
]
